plugins:
  - jest
  - prettier

env:
  node: true
  jest: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

extends:
  - airbnb-base
  - prettier
  - plugin:jest/recommended

rules:
  no-console: 0
